version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: proflow_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 03112003nM439565
      POSTGRES_DB: proflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
